DELETE FROM PUBLIC.STORAGE;

INSERT INTO PUBLIC.STORAGE (ID, NAME) VALUES(1, 'Центральный склад');
INSERT INTO PUBLIC.STORAGE (ID, NAME) VALUES(2, 'Симиренко');
INSERT INTO PUBLIC.STORAGE (ID, NAME) VALUES(3, 'Копыловская');
INSERT INTO PUBLIC.STORAGE (ID, NAME) VALUES(4, 'Уборевича');
INSERT INTO PUBLIC.STORAGE (ID, NAME) VALUES(5, 'Донецкая');


DELETE FROM PUBLIC.PROVIDER;
INSERT INTO PUBLIC.PROVIDER (ID, NAME) VALUES(1, 'Мегаполис');
INSERT INTO PUBLIC.PROVIDER (ID, NAME) VALUES(2, 'Свиточ');
INSERT INTO PUBLIC.PROVIDER (ID, NAME) VALUES(3, 'Олга-трейд');